### ISSUE TITLE
adding custom validators using new extension API

### ISSUE THREAD

**Issue by CagtayFabry** [asdf-format/asdf#1012]
What is the correct way to register custom validators now with the new extension API?

The documentation only mentions this in the deprecated old API section.
https://asdf.readthedocs.io/en/latest/asdf/extending/legacy.html#adding-custom-validators

**Comment by perrygreenfield** [comment]
Does the material under Extending ASDF answer your question, particularly in the subsections Resources and resource mappings, Converters,  Extensions, and Extension manifests?

**Comment by CagtayFabry** [comment]
We are looking into the steps necessary to move everything over to the new API so I looked through the new material (which is great btw.)

The validators do not get mentioned from what I see and from a few short looks over the new code I could not see where the validator hooks would be now.
We are just testing a few things so no hurry, but if there is a way would be great to transfer that over too.

**Comment by eslavich** [comment]
This feature hasn't been implemented in the new API yet, but it's something we'll need to support.  There's been some discussion of how we might implement it: https://github.com/asdf-format/asdf/issues/815#issuecomment-651051410

We need to put some thought into how we can restrict the scope of custom validators (maybe based on the schema's metaschema id) to avoid conflicts.

**Comment by CagtayFabry** [comment]
thanks for looking into that (and digging out some of the older issues)

I have switched everything over to the new API (which works really well) and just left an 'empty' legacy extension without any tag mappings to register the validators, seems to work nice so far 👍

**Comment by CagtayFabry** [comment]
closed via #1050
