### ISSUE TITLE
Fix Pytest 6 PytestUnraisableExceptionWarning

### ISSUE THREAD

**Issue by bnavigator** [asdf-format/asdf#1039]
Pytest 6.2 [introduced a new PytestUnraisableExceptionWarning](https://docs.pytest.org/en/6.2.x/usage.html#warning-about-unraisable-exceptions-and-unhandled-thread-exceptions), which are disabled for the `Warnings Treated as Exceptions` CI job in #1038. The cause for this should eventually be fixed.

See https://github.com/asdf-format/asdf/issues/1038#issuecomment-992974471

**Comment by WilliamJamieson** [comment]
This was likely resolved sometime before or in PR #1218.
