### ISSUE TITLE
Documentation theme has a small width for content

### ISSUE THREAD

**Issue by Cadair** [asdf-format/asdf#1061]
![image](https://user-images.githubusercontent.com/1391051/151967109-6e5b2a81-efb1-4e3f-a5f8-b753cfd2d156.png)

I get that having to wide text is bad, but so is having it too narrow :stuck_out_tongue:

**Comment by CagtayFabry** [comment]
agreed, might be worth tracking in [sphinx-asdf](https://github.com/asdf-format/sphinx-asdf/) as well

**Comment by WilliamJamieson** [comment]
This and other documentation issues were fixed by #1142.
