### ISSUE TITLE
The new converter interface's `SerializationContext` has no way of getting the file path of the file being read

### ISSUE THREAD

**Issue by Cadair** [asdf-format/asdf#1064]
In the DKIST tags I need to construct paths relative to the file being read, using the old `Extension` interface I did this with [`ctx.uri`](https://github.com/DKISTDC/dkist/blob/main/dkist/io/file_manager.py#L81) there appears to be no equivalent in the new API.

**Comment by eslavich** [comment]
Resolved by https://github.com/asdf-format/asdf/pull/1065
