### ISSUE TITLE
RTD documentation available online is still on 2.7.5 (stable)

### ISSUE THREAD

**Issue by marscher** [asdf-format/asdf#1102]
The stable branch on RTD should point to the latest release, right?

E.g. the change log shows 2.7.5 as last released version.
https://asdf.readthedocs.io/en/stable/asdf/changes.html?highlight=changes

**Comment by WilliamJamieson** [comment]
It is my understanding that the current stable release for asdf is 2.7.5. You can find the latest release at https://asdf.readthedocs.io/en/latest/. 

@eslavich can you confirm that 2.7.5 is the latest stable release?

**Comment by eslavich** [comment]
Right, 2.7.x has been our "stable" release for some time.  It's probably getting to be time to update that to one of the more recent 2.x releases.

**Comment by marscher** [comment]
Every project handles these terms differently. I'd consider a tested/released version "stable" and latest usually points to the master branch. Thanks for the clarification.

**Comment by WilliamJamieson** [comment]
@marscher, we recently moved the stable version to 2.11.x for a number of reasons. Hopefully, this makes things more clear.
