### ISSUE TITLE
jsonschema 4.x support

### ISSUE THREAD

**Issue by CagtayFabry** [asdf-format/asdf#1104]
as of now `asdf` is set to work with jsonschema 3 but explicitly does not support 4.x

https://github.com/asdf-format/asdf/blob/7eadb4f853bf48371dc3ac711dd68874d8eff40b/setup.cfg#L31

I am wondering what the specific reasons for this requirement are and how difficult it would be to relax the requirements to also allow `jsonschema=4` ?
The reason I am asking is that I ran into this problem when trying to use `asdf` in `JupyterLite` which already comes with `jsonschema=4`

This question is purely related to supporting the python package version of `jsonschema` and not about implementing any `JSON schema` features as mentioned in #747

**Comment by eslavich** [comment]
We have a draft going here for jsonschema 4.x support: https://github.com/asdf-format/asdf/pull/1105

It passes the weldx unit tests (🎉) but there are some other problems to work through.  Should be able to get that merged and released soon.

**Comment by CagtayFabry** [comment]
that is great, thank you for looking into it
