### ISSUE TITLE
Suggested new text to be added to the RTD documentation

### ISSUE THREAD

**Issue by KenMighell** [asdf-format/asdf#1114]
The file  
```https://asdf.readthedocs.io/en/stable/_sources/asdf/extensions.rst.txt ```
has the following hidden code after the presentation of the first YAML code block of the "An Example" subsubsection:
```
.. runcode:: hidden

    import os
    import asdf
    # This is a hack in order to get the example below to work properly
    __file__ = os.path.join(asdf.__path__[0], 'tests', 'data', 'fraction-1.0.0.yaml')
```
This hidden code has important information for the reader. Specifically, the YAML code block needs to be saved in the local working directory with the filename of "fraction-1.0.0.yaml" in order for the example to perform properly in a local working directory of their own choosing.

I suggest that this new note be added to to the file  
```https://asdf.readthedocs.io/en/stable/_sources/asdf/extensions.rst.txt ```  
just after the first YAML code block is presented (i.e., before the text "Then, the Python implementation of the tag class and extension class."):
```
.. note::

    The above YAML code needs to be saved in the local working directory with the
    filename of "fraction-1.0.0.yaml" in order for this example to perform properly.

```

The addition of this note should make life easier for the eager reader trying to replicate the results presented in the RTD documentation in a local working directory of their own choosing.

**Comment by WilliamJamieson** [comment]
Please feel free to contribute these changes by opening a pull request against asdf.

**Comment by KenMighell** [comment]
Should I make the changes to version 2.7.5 or to master?  

I refer above to the file ```extensions.rst``` which is version 2.7.5.  The closest to that file that I can find in version 2.10.1 is ```legacy.rst`` which is for the section "Deprecated extension API".

The online RTD documention at the GitHub repository at ```https://github.com/asdf-format/asdf``` is linked to ```http://asdf.readthedocs.io/``` which points to ```https://asdf.readthedocs.io/en/stable/``` .

The latest RTD documentation (```https://asdf.readthedocs.io/en/latest/```) is version 2.10.1 -- unfortunately that documentation is not as easily visible as the 2.7.5 (stable) version.

**Comment by WilliamJamieson** [comment]
@KenMighell I am closing this issue, please feel free to re-open it if you wish to discuss this further.
