### ISSUE TITLE
Possible security vulnerability in documentation generation

### ISSUE THREAD

**Issue by WilliamJamieson** [asdf-format/asdf#1120]
@pllim in side conversations pointed out that this portion: https://github.com/asdf-format/asdf/blob/aae8d9aeb5ff0bfe7248bfa595f256d4756ade18/docs/sphinxext/example.py#L44 of one of the custom sphinx directives in the asdf documentation could allow for arbitrary code execution in the documentation.

This vulnerability should be addressed soon.

**Comment by pllim** [comment]
I don't see any PR tied to this...

**Comment by jdavies-st** [comment]
Fixed in #1158

**Comment by pllim** [comment]
Is this really fixed or just kicked over to sphinx-asdf ?

**Comment by WilliamJamieson** [comment]
Essentially, yes; however, it is not really a security issue as it would require pushing a change to the ASDF repository and having the documentation CI approved for that person.
