### ISSUE TITLE
Update CI to run slow downstream tests prior to release

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1244]
To hopefully avoid post-release issues like https://github.com/asdf-format/asdf/issues/1239 where downstream package CI fails after release, what is a good way to add slow downstream tests to our CI?

Specifically, adding astropy tests with both `--open-files` and `--run-slow` args to pytest to replicate this tests might be a place to start:
https://github.com/astropy/astropy/blob/main/.github/workflows/ci_workflows.yml#L68

I am not familiar enough with github CI to know a good way to do this but perhaps there is a way to notice a *.*.x branch change and run the slower tests as these branches are created/changed prior to a release.

**Comment by WilliamJamieson** [comment]
> I guess you could use [this](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs):
> 
> ```
> on:
>   push:
>     branches:
>       - '**.x'
> ```
> 
> ([filter syntax docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet))

This is already being done.

**Comment by braingram** [comment]
Thanks @bilderbuchi
If I'm understanding we could copy from what we're doing in downstream.yml and make a slow_downstream.yml or pre_release_checks.yml that runs these tests.

**Comment by WilliamJamieson** [comment]
> Thanks @bilderbuchi If I'm understanding we could copy from what we're doing in downstream.yml and make a slow_downstream.yml or pre_release_checks.yml that runs these tests.

Or we could just add the `--open-files` and `--run-slow` flags to the `tox` environment run by our `downstream` tests...

**Comment by braingram** [comment]
It looks like if we had been using those options we would have caught the failure that motivated this issue:
https://github.com/astropy/astropy/actions/runs/3532958266/jobs/5927978680

I was originally thinking we were running the full astropy downstream tests (and enabling those options would slow down our CI) but reviewing the PR revealed we're only running only the astropy.io.misc.asdf tests which with these options still run faster than jwst.

Thanks for the fix!
