### ISSUE TITLE
Add upper pins to dependencies for LTS release

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1348]
@WilliamJamieson mentioned that dependabot might be useful for this.

**Comment by WilliamJamieson** [comment]
After reading @eslavich's suggested article in https://github.com/asdf-format/asdf/pull/1461#issuecomment-1455251472. I am convinced that upper pins on dependencies is a fundamentally bad idea, which will create more issues later on than it solves.

An alternate approach something like what I mentioned in https://github.com/asdf-format/asdf/pull/1461#issuecomment-1456363662:

> Maybe a solution is to add a requirements-tested.txt to 2.15.x when we sunset the 2.15.x version of ASDF? This way someone would have a configuration they could install if it starts breaking.

That is we include, some sort of "lock" file which is updated in the `2.15.x` branch which lays out (lower and) upper pins based on what versions we have actually tested for. Then hypothetically, future users can use this as a basis for generating working environments for working with legacy/unsupported versions of ASDF.

I think we can write some scripting to generate such a lock file from installing ASDF (without) pins. This could be run in CI to to periodically create PRs updating this file.

**Comment by braingram** [comment]
Closing per discussion here and https://github.com/asdf-format/asdf/pull/1461#issuecomment-1456900199
