### ISSUE TITLE
Clarify if minor versions are backwards compatible

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1366]
Our `Release Cycle and Major Dependency Support Policy`
https://asdf.readthedocs.io/en/latest/asdf/release_and_support.html
references APE2:
https://github.com/astropy/astropy-APEs/blob/main/APE2.rst
which describes how astropy does not follow semantic versioning and `feature versions` do not guarantee backwards compatibility.

We should clarify if ASDF follows the same versioning as astropy.

Specifically, do minor/feature releases (that increment the second number in the version) have any guarantee of backwards compatibility?

**Comment by braingram** [comment]
@WilliamJamieson to clarify, does ASDF have any gaurantee for backwards compatibility on minor version increases or does it follow APE2?

**Comment by WilliamJamieson** [comment]
My intention was indeed to follow APE2, which effectively is we will try our best to be semantic but that may not always work out.
