### ISSUE TITLE
add warnings on use of asdftool commands that require asdf.fits_embed

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1382]
Use of:

- asdftool extract
- asdftool remove-hdu

require asdf.fits_embed that will be deprecated and removed. As standard `DeprecationWarnings` will not be displayed, use of these tools should output a text warning to stderr.

**Comment by WilliamJamieson** [comment]
Some specific things that we know we need to address are pointed out in:

- https://github.com/asdf-format/asdf/pull/1337#discussion_r1110007498
- https://github.com/asdf-format/asdf/pull/1337#discussion_r1110008498
