### ISSUE TITLE
Find suitable new location for `format_tag`

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1404]
This is currently in the soon the be deprecated `asdf.types`:
https://github.com/asdf-format/asdf/blob/f726fe8a2ccaa3faf33713738510aa103836cfa3/asdf/types.py#L17-L29

It does not depend on the legacy type system and could be moved to a new location.

I've only found 1  use of this in `test_schema.py`:
https://github.com/asdf-format/asdf/blob/f726fe8a2ccaa3faf33713738510aa103836cfa3/asdf/tests/test_schema.py#L639

**Comment by WilliamJamieson** [comment]
I would say either put it in `testing.helpers`, `asdf.schema`, or `asdf.util`.

**Comment by WilliamJamieson** [comment]
My personal preference is for the helpers as it seems to be only used for testing.
