### ISSUE TITLE
`asdf.asdf.SerializationContext` not found

### ISSUE THREAD

**Issue by WilliamJamieson** [asdf-format/asdf#1565]
When building docs elsewhere, I get the following warning:
```
.from_yaml_tree:1: WARNING: py:class reference target not found: asdf.asdf.SerializationContext
```
when building API documentation using [`automodapi`](https://github.com/astropy/sphinx-automodapi).

Tracing this backwards, I believe the warning ultimately originates from: https://github.com/asdf-format/asdf/blob/c3e358886a41c36b81a2a26bd03aedc2720c9817/asdf/extension/_converter.py#L143

in ASDF. The warning occurs because there is no documentation for `asdf.asdf.SerializationContext` in the ASDF documentation for my documentation to link to. One can see this absence in the ASDF [documentation](https://asdf.readthedocs.io/en/latest/api/asdf.extension.Converter.html#asdf.extension.Converter.from_yaml_tree) too, where the `asdf.asdf.SerializationContext` does not link to anything (which it should).

ASDF needs to extend its API documentation to include the `asdf.asdf.SerializationContext` so that other projects can build documentation for objects subclassing `asdf.extension.Converter`.

**Comment by braingram** [comment]
Agreed!

xref: https://github.com/asdf-format/asdf/issues/1549
