### ISSUE TITLE
minor code smells in static code analysis

### ISSUE THREAD

**Issue by zacharyburnett** [asdf-format/asdf#1676]
when running SonarQube scanning on `asdf` in the `bench` repository, it found some minor code smells:

#### duplicates in regex character class
https://plsonarqube.stsci.edu/project/issues?tags=regex&branch=sonarscan&id=spacetelescope-bench&open=AYttO5qgrmNdxaPHqW54
https://github.com/asdf-format/asdf/blob/ecb4d4f6308738c4de0da8eec5bd272e90f3954e/asdf/_jsonschema/tests/_suite.py#L176

#### variable name shadows builtin
https://plsonarqube.stsci.edu/project/issues?tags=pitfall&branch=sonarscan&id=spacetelescope-bench
https://github.com/asdf-format/asdf/blob/ecb4d4f6308738c4de0da8eec5bd272e90f3954e/asdf/_jsonschema/_legacy_validators.py#L138
https://github.com/asdf-format/asdf/blob/ecb4d4f6308738c4de0da8eec5bd272e90f3954e/asdf/_jsonschema/_legacy_validators.py#L154
https://github.com/asdf-format/asdf/blob/ecb4d4f6308738c4de0da8eec5bd272e90f3954e/asdf/_jsonschema/tests/test_validators.py#L332
https://github.com/asdf-format/asdf/blob/ecb4d4f6308738c4de0da8eec5bd272e90f3954e/asdf/_tests/test_yaml.py#L284
https://github.com/asdf-format/asdf/blob/ecb4d4f6308738c4de0da8eec5bd272e90f3954e/asdf/commands/edit.py#L101
https://github.com/asdf-format/asdf/blob/ecb4d4f6308738c4de0da8eec5bd272e90f3954e/asdf/compression.py#L265
https://github.com/asdf-format/asdf/blob/ecb4d4f6308738c4de0da8eec5bd272e90f3954e/asdf/generic_io.py#L888
https://github.com/asdf-format/asdf/blob/ecb4d4f6308738c4de0da8eec5bd272e90f3954e/asdf/generic_io.py#L897
https://github.com/asdf-format/asdf/blob/ecb4d4f6308738c4de0da8eec5bd272e90f3954e/asdf/generic_io.py#L902

**Comment by braingram** [comment]
Do these cause any issue for the benchmarking?

Looking over the "smells" I see:
- several in the copied/vendorized jsonschema
- uses of the word 'buffer'. I guess this is too generic of a word for sonarqubes liking?

**Comment by zacharyburnett** [comment]
> Do these cause any issue for the benchmarking?
> 
> Looking over the "smells" I see:
> 
> * several in the copied/vendorized jsonschema
> * uses of the word 'buffer'. I guess this is too generic of a word for sonarqubes liking?

yeah it had a bunch of even more minor (minor-er?) suggestions that I ignored, but in this case it said `cmp`, `type`, and `buffer` are apparently already built-in functions / object names, so that might cause insidious errors

**Comment by braingram** [comment]
If these aren't an issue for the benchmarking I'm inclined to leave the code as-is. The `cmp` and `type` uses are within the vendorized jsonschema which will hopefully be replaced with a dependency if jsonschema re-adds the features required by asdf.

As far as I'm aware,`buffer` is a builtin only in python 2, perhaps sonarqube isn't scanning for only python 3 issues?

**Comment by zacharyburnett** [comment]
ok, sounds good to me then! I'll mark the issues as "ignore" in sonarqube
