### ISSUE TITLE
ignore_version_mismatch doesn't appear to be used?

### ISSUE THREAD

**Issue by astrofrog** [asdf-format/asdf#1811]
I am getting warnings about mismatched schema versions regardless of whether ``ignore_version_mismatch`` is set or not in ``open``. It doesn't look like this setting is actually used anywhere in the asdf package?

**Comment by braingram** [comment]
Thanks for opening the issue. What's the error you're seeing? Also what package versions are you using (a full `pip freeze` output would be helpful)?

**Comment by braingram** [comment]
Thanks also for pointing out that this setting is unused. I opened an issue to track it's removal. I is a left-over from the legacy extension API that was removed in asdf 3.0.0.

**Comment by astrofrog** [comment]
@braingram - well no error message as such, just that I would like to actually ignore the version mismatch issues. What is the recommended way to do that now if that option is deprecated?

**Comment by braingram** [comment]
What's the warning message?

**Comment by astrofrog** [comment]
```
asdf.exceptions.AsdfPackageVersionWarning: File 'file:///home/runner/work/reproject/reproject/.tox/py312-test-devdeps/lib/python3.12/site-packages/reproject/tests/data/aia_171_level1.asdf' was created with extension URI 'asdf://asdf-format.org/core/extensions/core-1.5.0' (from package asdf-astropy==0.6.1), but older package (asdf-astropy==0.6.1.dev24+gfa5f1f4) is installed.
```

**Comment by astrofrog** [comment]
which is frustrating because in fact I am using the development version of asdf-astropy which is more recent than 0.6.1.

**Comment by braingram** [comment]
Thanks! I think that also means the main branch of asdf-astropy could use a newer (0.6.2) dev tag. I'll give that a look.

One way to ignore these warnings would be to:
```python
import asdf
import warnings
warnings.simplefilter("ignore", category=asdf.exceptions.AsdfPackageVersionWarning)
# your code here
```

**Comment by braingram** [comment]
I added a 0.6.2.dev tag to asdf-astropy so I think pulling the tags should also fix the issue.

**Comment by astrofrog** [comment]
Thanks! Weirdly I thought setuptools-scm was smart enough to use the next version for the start of the version string. I'll need to take a look!

**Comment by braingram** [comment]
Let me know if you run into any issues. I'm going to close this PR but feel free to re-open it. Also, thanks again for opening the issue!
