### ISSUE TITLE
[3.4.0] test_access_after_del fails with Python 3.13

### ISSUE THREAD

**Issue by olebole** [asdf-format/asdf#1834]
We currently test-build all packages for Python 3.13, where the python-asdf package failed . When running the CI test during build, the **test_access_after_del** test fails (with 3.12.6, the test passes):

```python
___________________________ test_access_after_del _____________________________
tmp_path = PosixPath('/tmp/pytest-of-debusine-worker/pytest-0/test_access_after_del0')

    def test_access_after_del(tmp_path):
        fn = tmp_path / "test.asdf"
    
        arr = np.arange(42)
        tree = {"a": {"b": arr}}
        asdf.AsdfFile(tree).write_to(fn)
    
        with asdf.open(fn, lazy_tree=True) as af:
            d = af["a"]
    
        del af
    
>       with pytest.raises(asdf.exceptions.AsdfLazyReferenceError, match="Failed to resolve"):
E       Failed: DID NOT RAISE <class 'asdf.exceptions.AsdfLazyReferenceError'>
```

The other tests pass.

This was reported as [Debian#1082195](https://bugs.debian.org/1082195).

# System information

asdf version: 3.4.0
python version: 3.13.0rc2
operating system: Debian testing+experimental

**Comment by braingram** [comment]
Thanks for opening the issue.

Oddly we haven't seen this so far in our [CI tests using 3.13](https://github.com/asdf-format/asdf/actions/runs/10478407451/job/29021865145). I think there's a way to make that test more robust and I'll try to use the run you linked (Thanks!) to reproduce it.

Is it possible to skip that test for packaging 3.4.0 until we can make a new release?

**Comment by olebole** [comment]
There is no urgent need to act, because we don't have Python 3.13 yet in our unstable archive, and I don't know the timeline when it will be. If we start to move to 3.13 with our packages and there is no fix, I will just disable the test.
