### ISSUE TITLE
write_to does not work when working cross system

### ISSUE THREAD

**Issue by BradleySappington** [asdf-format/asdf#1850]
# Description of the problem

The traceback code:
`
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 22
     19 af = asdf.AsdfFile(tree)
     21 # Write the data to a new file
---> 22 af.write_to("example.asdf")

File ~/miniconda3/envs/test/lib/python3.11/site-packages/asdf/_asdf.py:1340, in AsdfFile.write_to(self, fd, all_array_storage, all_array_compression, compression_kwargs, pad_blocks, include_block_index, version)
   1337     self.version = version
   1339 try:
-> 1340     with generic_io.get_file(fd, mode="w") as fd:
   1341         self._serial_write(fd, pad_blocks, include_block_index)
   1342 finally:

File ~/miniconda3/envs/test/lib/python3.11/site-packages/asdf/generic_io.py:1142, in get_file(init, mode, uri, close)
   1138         except FileNotFoundError as e:
   1139             # atomic_open will create an Exception with an odd looking path
   1140             # overwrite the error message to make it more informative
   1141             e.filename = realpath
-> 1142             raise e
   1144         return RealFile(fd, mode, close=True, uri=uri)
   1146 if isinstance(init, io.BytesIO):

File ~/miniconda3/envs/test/lib/python3.11/site-packages/asdf/generic_io.py:1135, in get_file(init, mode, uri, close)
   1129 realpath = (
   1130     str(init)
   1131     if sys.platform.startswith("win") and parsed.scheme in string.ascii_letters
   1132     else url2pathname(parsed.path)
   1133 )
   1134 try:
-> 1135     fd = atomicfile.atomic_open(realpath, realmode) if mode == "w" else open(realpath, realmode)
   1137     fd = fd.__enter__()
   1138 except FileNotFoundError as e:
   1139     # atomic_open will create an Exception with an odd looking path
   1140     # overwrite the error message to make it more informative

File ~/miniconda3/envs/test/lib/python3.11/site-packages/asdf/_extern/atomicfile.py:135, in atomic_open(filename, mode)
    133 if mode in ('r', 'rb', 'r+', 'rb+', 'a', 'ab'):
    134     raise TypeError('Read or append modes don\'t work with atomic_open')
--> 135 f = tempfile.NamedTemporaryFile(mode, prefix='.___atomic_write',
    136                                 dir=os.path.dirname(filename),
    137                                 delete=False)
    138 return _AtomicWFile(f, f.name, filename)

File ~/miniconda3/envs/test/lib/python3.11/tempfile.py:563, in NamedTemporaryFile(mode, buffering, encoding, newline, suffix, prefix, dir, delete, errors)
    561     return fd
    562 try:
--> 563     file = _io.open(dir, mode, buffering=buffering,
    564                     newline=newline, encoding=encoding, errors=errors,
    565                     opener=opener)
    566     try:
    567         raw = getattr(file, 'buffer', file)

File ~/miniconda3/envs/test/lib/python3.11/tempfile.py:560, in NamedTemporaryFile.<locals>.opener(*args)
    558 def opener(*args):
    559     nonlocal name
--> 560     fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
    561     return fd

File ~/miniconda3/envs/test/lib/python3.11/tempfile.py:256, in _mkstemp_inner(dir, pre, suf, flags, output_type)
    254 _sys.audit("tempfile.mkstemp", file)
    255 try:
--> 256     fd = _os.open(file, flags, 0o600)
    257 except FileExistsError:
    258     continue    # try again

FileNotFoundError: [Errno 2] No such file or directory: 'example.asdf'`

# Example of the problem
If I run the example code in your readme on my laptop and locally it works fine.  However if I navigate to an external system ('/grp/roman/mydirectory') and run from my laptop, the example fails.  I have permissions to create files in this drive and can do so (and if I do the write_to still fails)

The code that I'm running:
In [1]: import asdf
   ...: import numpy as np
   ...:
   ...: # Create some data
   ...: sequence = np.arange(100)
   ...: squares = sequence**2
   ...: random = np.random.random(100)
   ...:
   ...: # Store the data in an arbitrarily nested dictionary
   ...: tree = {
   ...:     "foo": 42,
   ...:     "name": "Monty",
   ...:     "sequence": sequence,
   ...:     "powers": {"squares": squares},
   ...:     "random": random,
   ...: }
   ...:
   ...: # Create the ASDF file object from our data tree
   ...: af = asdf.AsdfFile(tree)
   ...:
   ...: # Write the data to a new file
   ...: af.write_to("example.asdf")

# System information

asdf version:
3.5.0
python version:
3.11.8
operating system:
macOS 13.6.9

**Comment by braingram** [comment]
Thanks for opening the issue.

Unfortunately the mapping of central storage to local systems can result in the directory not appearing consistently (and periodic failures to access or create files). This extends to all file access not (including `ls`).

What are the permissions for the directory you're attempting to write to?

**Comment by BradleySappington** [comment]
drwxr-sr-x

**Comment by braingram** [comment]
Thanks.

If you run the following in that directory does it succeed?

```python
import asdf

with open("example.asdf", "wb") as f:
    f.write(b"abc")

asdf.AsdfFile({"foo": "abc"}).write_to("example.asdf")
```

**Comment by BradleySappington** [comment]
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 6
      3 with open("example.asdf", "wb") as f:
      4     f.write(b"abc")
----> 6 asdf.AsdfFile({"foo": "abc"}).write_to("example.asdf")

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/site-packages/asdf/_asdf.py:1340, in AsdfFile.write_to(self, fd, all_array_storage, all_array_compression, compression_kwargs, pad_blocks, include_block_index, version)
   1337     self.version = version
   1339 try:
-> 1340     with generic_io.get_file(fd, mode="w") as fd:
   1341         self._serial_write(fd, pad_blocks, include_block_index)
   1342 finally:

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/site-packages/asdf/generic_io.py:1142, in get_file(init, mode, uri, close)
   1138         except FileNotFoundError as e:
   1139             # atomic_open will create an Exception with an odd looking path
   1140             # overwrite the error message to make it more informative
   1141             e.filename = realpath
-> 1142             raise e
   1144         return RealFile(fd, mode, close=True, uri=uri)
   1146 if isinstance(init, io.BytesIO):

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/site-packages/asdf/generic_io.py:1135, in get_file(init, mode, uri, close)
   1129 realpath = (
   1130     str(init)
   1131     if sys.platform.startswith("win") and parsed.scheme in string.ascii_letters
   1132     else url2pathname(parsed.path)
   1133 )
   1134 try:
-> 1135     fd = atomicfile.atomic_open(realpath, realmode) if mode == "w" else open(realpath, realmode)
   1137     fd = fd.__enter__()
   1138 except FileNotFoundError as e:
   1139     # atomic_open will create an Exception with an odd looking path
   1140     # overwrite the error message to make it more informative

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/site-packages/asdf/_extern/atomicfile.py:135, in atomic_open(filename, mode)
    133 if mode in ('r', 'rb', 'r+', 'rb+', 'a', 'ab'):
    134     raise TypeError('Read or append modes don\'t work with atomic_open')
--> 135 f = tempfile.NamedTemporaryFile(mode, prefix='.___atomic_write',
    136                                 dir=os.path.dirname(filename),
    137                                 delete=False)
    138 return _AtomicWFile(f, f.name, filename)

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/tempfile.py:580, in NamedTemporaryFile(mode, buffering, encoding, newline, suffix, prefix, dir, delete, errors)
    578     return fd
    579 try:
--> 580     file = _io.open(dir, mode, buffering=buffering,
    581                     newline=newline, encoding=encoding, errors=errors,
    582                     opener=opener)
    583     try:
    584         raw = getattr(file, 'buffer', file)

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/tempfile.py:577, in NamedTemporaryFile.<locals>.opener(*args)
    575 def opener(*args):
    576     nonlocal name
--> 577     fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
    578     return fd

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/tempfile.py:257, in _mkstemp_inner(dir, pre, suf, flags, output_type)
    255 _sys.audit("tempfile.mkstemp", file)
    256 try:
--> 257     fd = _os.open(file, flags, 0o600)
    258 except FileExistsError:
    259     continue    # try again

FileNotFoundError: [Errno 2] No such file or directory: 'example.asdf'

**Comment by braingram** [comment]
Thanks again. You may currently have the elusive configuration where this failure is reproducible. Thank you for running these tests. What happens if you run the following?
```python
import tempfile

with tempfile.NamedTemporaryFile("w", prefix="test_", dir=".") as f:
    f.write("abc")
```

**Comment by braingram** [comment]
Good! So that one looks to have worked. How about:
```python
import tempfile

with tempfile.NamedTemporaryFile("w", prefix=".___atomic_write", dir=".") as f:
    f.write("abc")
```

**Comment by BradleySappington** [comment]
In [4]: import tempfile
   ...:
   ...: with tempfile.NamedTemporaryFile("w", prefix=".___atomic_write", dir="."
   ...: ) as f:
   ...:     f.write("abc")
   ...:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[4], line 3
      1 import tempfile
----> 3 with tempfile.NamedTemporaryFile("w", prefix=".___atomic_write", dir=".") as f:
      4     f.write("abc")

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/tempfile.py:580, in NamedTemporaryFile(mode, buffering, encoding, newline, suffix, prefix, dir, delete, errors)
    578     return fd
    579 try:
--> 580     file = _io.open(dir, mode, buffering=buffering,
    581                     newline=newline, encoding=encoding, errors=errors,
    582                     opener=opener)
    583     try:
    584         raw = getattr(file, 'buffer', file)

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/tempfile.py:577, in NamedTemporaryFile.<locals>.opener(*args)
    575 def opener(*args):
    576     nonlocal name
--> 577     fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
    578     return fd

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/tempfile.py:257, in _mkstemp_inner(dir, pre, suf, flags, output_type)
    255 _sys.audit("tempfile.mkstemp", file)
    256 try:
--> 257     fd = _os.open(file, flags, 0o600)
    258 except FileExistsError:
    259     continue    # try again

FileNotFoundError: [Errno 2] No such file or directory: '/System/Volumes/Data/grp/roman/bsappington/wfi_ref_pipeline/wfi_reference_pipeline/.___atomic_writejpqkf_s7'

**Comment by braingram** [comment]
Interesting. So it looks like python can't make a temporary file in that directory that starts with ".___atomic_write". Does the following work?
```python
with open(".___atomic_writeabc123", "wb") as f:
    f.write("abc")
```
I also wonder, does the previous example work if you're in /grp/roman/bsappington/wfi_ref_pipeline/wfi_reference_pipeline/ instead of the similar path starting with /System/Volumes?

**Comment by BradleySappington** [comment]
In [5]: with open(".___atomic_writeabc123", "wb") as f:
   ...:     f.write("abc")
   ...:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[5], line 1
----> 1 with open(".___atomic_writeabc123", "wb") as f:
      2     f.write("abc")

File ~/miniconda3/envs/wfirefpipe/lib/python3.11/site-packages/IPython/core/interactiveshell.py:324, in _modified_open(file, *args, **kwargs)
    317 if file in {0, 1, 2}:
    318     raise ValueError(
    319         f"IPython won't let you open fd={file} by default "
    320         "as it is likely to crash IPython. If you know what you are doing, "
    321         "you can use builtins' open."
    322     )
--> 324 return io_open(file, *args, **kwargs)

FileNotFoundError: [Errno 2] No such file or directory: '.___atomic_writeabc123'

**Comment by BradleySappington** [comment]
In [2]: pwd
Out[2]: '/System/Volumes/Data/grp/roman/bsappington/wfi_ref_pipeline/wfi_reference_pipeline'

In [3]: exit
(wfirefpipe) bsappington$ pwd
/grp/roman/bsappington/wfi_ref_pipeline/wfi_reference_pipeline

**Comment by braingram** [comment]
Does your last comment mean ipython says your working directory is `/System/Volumes...` but bash says its `/grp/roman...`?

**Comment by BradleySappington** [comment]
yes, pwd in ipython was `/System/Volumes` but when I exit the ipython session it is the alias that is displayed

**Comment by braingram** [comment]
Thanks! I think that gave me enough information to reproduce this locally. There are some odd things going on and it's unclear what's the root cause of the issue (or if it's a combination of things) but it may be related to:
- the mount mirroring (`/grp` vs `/Volumes`) creating issues for temporary files
- the network mount filtering out `.___` files
- overuse of temporary files in asdf (in this case there's no need to use a temporary file but asdf uses it in part to avoid producing corrupt files on partial writes)

Would you try the following (all within the same ipython session):
```python
import asdf, tempfile

try:
    asdf.AsdfFile({"foo": 123}).write_to("foo.asdf")
except:
    pass

for _ in range(3):
    try:
        tempfile.NamedTemporaryFile("w", prefix=".atomic_write", dir=".")
    except:
        pass

asdf.AsdfFile({"foo": 123}).write_to("foo.asdf")
```

If I run the above code the session then is able to write files without issue. Presumably something in that above mess is enough to "wake up" the mount and get it into a working state.

**Comment by BradleySappington** [comment]
In [1]: import asdf, tempfile
   ...:
   ...: try:
   ...:     asdf.AsdfFile({"foo": 123}).write_to("foo.asdf")
   ...: except:
   ...:     pass
   ...:
   ...: for _ in range(3):
   ...:     try:
   ...:         tempfile.NamedTemporaryFile("w", prefix=".atomic_write", dir=".")
   ...:     except:
   ...:         pass
   ...:
   ...: asdf.AsdfFile({"foo": 123}).write_to("foo.asdf")

In [2]: ls
README.md         dev_scripts/      examples/         pyproject.toml    src/
build/            example.asdf      foo.asdf          requirements.txt

**Comment by braingram** [comment]
Thanks. I think this all points to something odd going on with the central store mount (since the writes initially fail but then seem to fix themselves after writing to a different file). @jhunkeler mentioned that this might be related to https://en.wikipedia.org/wiki/AppleSingle_and_AppleDouble_formats

It does seem to be specific to the creation of a file starting with `._`. If I start a fresh python session (doesn't need to be ipython) with my current directory being a location on the network drive then calling `open('._foo', 'wb')` will fail until I call `open('.foo', 'wb')` (after which the call to `open('._foo', 'wb')` will succeed.

**Comment by braingram** [comment]
FWIW this is not exclusively a python problem again pointing to issues with the central store mount:
```c
#include <stdio.h>
FILE *fptr;

int main() {
  fptr = fopen(".bam", "w");
  if (fptr == NULL) {
    printf("failed to create .bam\n");
    return 1;
  }
  fprintf(fptr, "abc");
  fclose(fptr);
  fptr = fopen("._foo", "w");
  if (fptr == NULL) {
    printf("failed to create ._foo\n");
    return 1;
  }
  fprintf(fptr, "abc");
  fclose(fptr);
  return 0;
}
```
The above C code succeeds but fails if `.bam` is not created before `._foo`.
