### ISSUE TITLE
Should asdf-standard be a fully-fledged python package?

### ISSUE THREAD

**Issue by drdavella** [asdf-format/asdf#397]
This would enable `asdf-standard` to be installed using `setuptools`, so it would no longer need to be packaged as a submodule of the `asdf` repository. The `asdf` module could then import `asdf-standard` in order to determine the location of schema files.

Of course, this would not be useful for implementations of ASDF in languages other than Python, but I don't think that should necessarily prevent it from being done.

cc @nden, @perrygreenfield, @eteq

**Comment by drdavella** [comment]
This might become easier now with Python 3.7: see #514.

**Comment by nden** [comment]
It is now a python package.
