### ISSUE TITLE
Support and/or enforce explicit versioning of extensions

### ISSUE THREAD

**Issue by drdavella** [asdf-format/asdf#479]
It would be useful if extensions explicitly declared versions. While software package versions are a good proxy, it is possible for package versions to change without making any updates to schemas/tags/extensions. Explicitly versioning the extensions themselves to indicate any tag/schema updates could help make it easier to reason about versions that are required to read particular files.

This could probably make it in by 2.0.0, although I need to think through the implications, API, etc.

**Comment by braingram** [comment]
I'm not sure I can point to a single PR but this issue appears to be addressed with the new extension API where extensions have uris that contain versions.
See: https://asdf.readthedocs.io/en/latest/asdf/extending/extensions.html#basics
Please feel free to reopen this if I'm mistaken.
