### ISSUE TITLE
Resolver should use only the first matching extension mapper

### ISSUE THREAD

**Issue by jdavies-st** [asdf-format/asdf#751]
Currently a tag and/or URI in a schema gets mapped through the resolver of all extensions chained together, end to end before the resulting string (which should represent an on-file schema) gets opened.

It might be better to have this work more like a regex, where the resolvers are tried in a particular order, and once a particular resolver actually resolves the string (i.e changes it), it stops, and doesn't pass through the remaining ones.

Or it's possible that the resolver could return a `True` or `False` if the resolver produces a match?

The idea would be to try to prevent one installed extension from hosing other installed extensions. Currently there's not a robust way to prevent this.  Not sure if this could prevent issues like https://github.com/astropy/specutils/issues/465, but it is possible.  Ordering would probably matter.  More thought is needed.

ht: @eslavich

**Comment by eslavich** [comment]
Closing this, since the new plugin for schemas works on the basis of matching exact URIs and thus avoids the problem.
