### ISSUE TITLE
Add warning when schema $ref is a tag

### ISSUE THREAD

**Issue by eslavich** [asdf-format/asdf#752]
It looks to me like `$ref` values were intended to be URIs or URI fragments, and it's only a quirk of the load_schema function in this library that tag values are resolved at all.  Consider adding a check to the pytest plugin that fails when `$ref` is set to a tag, and a deprecation warning to load_schema so that we can encourage correct use of `$ref`.

**Comment by jdavies-st** [comment]
And this is because the `tag_to_url_mapping and `url_mapping` are always chained together and operate on both tags and URLs?
