### ISSUE TITLE
Consider replacing vendorized RangeHTTPServer

### ISSUE THREAD

**Issue by eslavich** [asdf-format/asdf#798]
We've included a vendorized copy of RangeHTTPServer for testing with an http server, but it seems like there must be a more standard tool we can use for that purpose.  @jdavies-st suggests requests-mock as a possibility.

**Comment by jdavies-st** [comment]
While we're at, we've also vendorized `extern.decorators` from Sunpy which we don't use either.  That can probably just be removed.
