### ISSUE TITLE
Replace Travis with GitHub actions

### ISSUE THREAD

**Issue by eslavich** [asdf-format/asdf#818]
Some dissatisfying aspects of Travis:

- The s390x build has always been flaky, but lately it's been failing consistently (timeouts during install)
- GitHub integration has degenerated in recent months, leaving the build status icons out of sync
- I just burned a bunch of time troubleshooting the MacOS build after Travis made an unannounced change to the container

Enough reason to give GitHub actions a try -- since we already have tox set up, it should be straightforward.

**Comment by Cadair** [comment]
Github actions is great, I would also say that Azure pipelines is nice, and there is a bunch of work Tom and I did to make it easy in https://github.com/OpenAstronomy/azure-pipelines-templates

In reality there isn't a huge amount to choose between them.

**Comment by jdavies-st** [comment]
Here's an action for s390x jobs.

https://github.com/marketplace/actions/run-on-architecture
