### ISSUE TITLE
relative uri path when using "tag" validator

### ISSUE THREAD

**Issue by CagtayFabry** [asdf-format/asdf#823]
Es mentioned in https://github.com/asdf-format/asdf/issues/814#issuecomment-650255706 `tag` can be used to validate instead of `$ref`

When switching to `tag` validation I noticed relative schema reference does not work (it does with `$ref`)
```yaml
$ref: "../core/ndarray-1.0.0" # works
tag: "../core/ndarray-1.0.0" # throws validation error because no exact match
```

I guess tag validation happens here which would explain the behavior (looking for full matching tag string):
https://github.com/asdf-format/asdf/blob/4b0388d668f4e8bd181a97000ef828cd0b1b72e2/asdf/schema.py#L76-L87

Is there any helper function that can resolve relative tag/uri strings in the current ASDF library that could be used here?

**Comment by eslavich** [comment]
I don't think there's a general solution to that, unless we introduce some new field to the schema that defines a base against which tags should be resolved.  The `$ref` values are resolved against the schema's `id`, but there may not be a 1:1 correspondence between an id URI and a tag URI, so we can't infer the tag from the schema id in all cases.

**Comment by CagtayFabry** [comment]
I see, didn't think about `id` - `tag` not always having a 1:1 relation so yeah not as simple as I thought it might be
I will close this for now, thank you for clarifying
