### ISSUE TITLE
[Bug] Wrong seriaization of higher dimensional ndarrays that have been transposed multiple times

### ISSUE THREAD

**Issue by vhirtham** [asdf-format/asdf#826]
Have a look at the following script:

~~~ python
from io import BytesIO

import asdf
import numpy as np


def print_array_information(name, array):
    print(name)
    print("---")
    print("data[0]")
    print(array[0])
    print(f"data c_contiguous: {array.flags.c_contiguous}")
    if array.base is not None:
        print("base[0]")
        print(array.base[0])
        print(f"base c_contiguous: {array.base.flags.c_contiguous}")
    else:
        print("base is 'None'")
    print("\n")


arr1 = np.array([[[0, 1], [-1, 0]], [[0, 1], [-1, 0]]], dtype=float)
print_array_information("array", arr1)


arr2 = arr1.transpose(0, 2, 1)
print_array_information("transposed array", arr2)


arr3 = arr2 * 1
print_array_information("multiplied transposed array", arr3)


arr4 = arr3.transpose(0, 2, 1)
print_array_information("transposed multiplied transposed array", arr4)


assert np.array_equal(arr1, arr4)


tree = {"root": arr4}

# Write the data to buffer
with asdf.AsdfFile(tree, ignore_version_mismatch=False,) as ff:
    buff = BytesIO()
    ff.write_to(buff)
    buff.seek(0)

# read back data from ASDF file contents in buffer
with asdf.open(buff, copy_arrays=True, lazy_load=False) as af:
    data = af.tree
    print(data["root"])
    assert np.array_equal(arr4, data["root"])
~~~

All it does is that it creates a 3d array, swaps the 2 innermost dimensions, multiplies it by 1, swaps the innermost dimensions again, and writes the resulting array `arr4`, which is equal to the original array `arr1`, to an asdf file/buffer. If you restore the data from the file/buffer, the assertion `assert np.array_equal(arr4, data["root"])` fails. Observing the data shows, that the innermost dimensions are transposed. The outputs of the `print_array_information` method show where the issue comes from. 

relevant `arr1` output:
~~~
data c_contiguous: True
base is 'None'
~~~

relevant `arr2` output:
~~~
data c_contiguous: False
base[0]
[[ 0.  1.]
 [-1.  0.]]
base c_contiguous: True
~~~

relevant `arr3` output:
~~~
data c_contiguous: False
base is 'None'
~~~

relevant `arr4` output:
~~~
data c_contiguous: True
base[0]
[[ 0. -1.]
 [ 1.  0.]]
base c_contiguous: False
~~~

The problem here is the following: Transposing a matrix "destroys" the "c continuity". Transposing it twice restores it. Multiplication, division, and probably several other operations keep the current "c continuity"/data interpretation but write to a new block of memory, which resets the arrays `base`.
Because of this,  `arr3.base` is `None` but `arr3.flags.c_contiguous` is `False` as it is for `arr2`, even though it uses a fresh memory location. Now if we transpose again, `arr4` has  `c_contiguous` data but a non `c_contiguous` base. Why is this a problem and causes an error?

I have looked into the ndarray `to_tree` method.

https://github.com/asdf-format/asdf/blob/f5b5900dc45f0668d04281203ae1d9a1c0f8ea1c/asdf/tags/core/ndarray.py#L418-L432

Here you only check if `data` is  `c_contiguous` (line 425) and correct it if not. However, in the `find_or_create_block_for_array` method, which is used afterwards to get the data that should be written into the file (if I am not mistaken), you use the data of `base` (line738 - below) without checking if it's underlying order/"c continuity" is still correct:

https://github.com/asdf-format/asdf/blob/f5b5900dc45f0668d04281203ae1d9a1c0f8ea1c/asdf/block.py#L716-L745

I guess this is what causes the error. Maybe a simple fix would be to add this:

~~~
if not base.flags.c_contiguous:
    base = np.array(base)
~~~

or something similar after line 738, but I don't know if that would break some other stuff. However, creating a new numpy array with the "constructor"/`__init__` method will fix the `c_contiguous` issue of the base, since it resets it. When you replace `arr4 = arr3.transpose(0, 2, 1)` with `arr4 = np.array(arr3.transpose(0, 2, 1))` in the script, the assertion passes.

**Additional Notes**

If one removes the second matrix or reduces the dimension to 2d, the error disappears. So it seems to be a problem of higher dimensional arrays.

For reference, here are the version numbers of my setup:

~~~
Python Version: 3.7.7
Numpy Version: 1.18.1
ASDF Version: 2.6.0
~~~

**Comment by eslavich** [comment]
Thanks for the thorough report!  I opened #827 with an idea for a fix, though I'm not sure if that's the best approach.

@perrygreenfield in the library we take pains to only write out the base array in C order or Fortran order, but I don't see anything in the ASDF Standard that requires that behavior.  In this case the original base array is in neither order, so we convert it to C order before writing.  The conversion doesn't play well with the strides on the ndarray view since they were specified relative to the original memory order of the base array.

I can think of a few options:

1) Write out the base array in its original memory order
2) Continue converting the base array to C order, and modify the strides on the ndarray view to match
3) Make a copy of the view array when we detect that the base array is not in C or Fortran order

My PR implements option 1).

**Comment by perrygreenfield** [comment]
Option 1 seems like the most foolproof. I can see problems with the others if there are multiple views in the asdf tree to the same array, wouldn't you. Either you must edit all the views to be consistent, or if making copies, the assumption that it is a view is broken.  Or do I misunderstand?

**Comment by eslavich** [comment]
We might be able to edit all the views to be consistent, since the base array isn't modified until later on in the write process -- but I'd rather avoid that anyway because determining the correct strides for the new form of the base array sounds complicated.
