### ISSUE TITLE
Document new plugin APIs

### ISSUE THREAD

**Issue by eslavich** [asdf-format/asdf#880]
We need a guide, similar to extensions.rst, on how to use the new plugin APIs.  Specifically:

- Resource mappings, what they are and how to implement them in a package, `DirectoryResourceMapping` use, providing mappings via entry points, troubleshooting missing resources
- The new `Extension` class, how it relates to `Converter` and resource mappings, providing an extension via entry points
- `Converter`, troubleshooting tag support

Once complete we'll need to link in the new material from developer_overview.rst.

**Comment by CagtayFabry** [comment]
regarding this snippet from #819 
```python
import asdf

schema = """
type: object
properties:
  bar:
    type: integer
"""

asdf.get_config().add_resource_mapping({"http://somewhere.org/schemas/foo-1.0.0": schema})
```
Could you provide a simple example how to add a resource mapping by providing a path to a complete asdf schema file?
In theory I would like to do something like this:
```python
asdf.get_config().add_resource_mapping({"http://somewhere.org/schemas/foo-1.0.0": Path("./foo-1.0.0.yaml")})
```
Is there any function that extracts the schema contents from a file?

**Comment by eslavich** [comment]
We don't have a dedicated method for that (yet), so this is how I'd do it:

```python
asdf.get_config().add_resource_mapping({
  "http://somewhere.org/schemas/foo-1.0.0": Path("./foo-1.0.0.yaml").read_bytes(),
})
```

Is that reasonable?  In any case I agree the documentation should include this kind of example.

**Comment by CagtayFabry** [comment]
Great that it's that easy 👍 

My misconception following the example was that the schema had to be stripped of all YAML/ASDF header lines but if the complete file can be added as a mapping this should make it very simple.
Thank you for clarifying
