### ISSUE TITLE
Broken link in readthedocs documentation

### ISSUE THREAD

**Issue by vhirtham** [asdf-format/asdf#892]
I just stumbled over a broken link in your readthedocs documentation in the [Creating custom schemas section](https://asdf.readthedocs.io/en/stable/asdf/extensions.html#creating-custom-schemas). If you click on the `ASDF Standard` link it will redirect you to `https://asdf-standard.readthedocs.io/en/latest/extending.html` which does not exist (yet? anymore?).

**Comment by eslavich** [comment]
Oops, thanks for pointing that out!  Looks like we dropped that page from the standard docs a while ago.  Seems like the link should be updated to point to this page instead:

https://asdf-standard.readthedocs.io/en/latest/schemas.html

**Comment by vhirtham** [comment]
Thanks for the correct link. :)

**Comment by eslavich** [comment]
Fixed by #893
