### ISSUE TITLE
wrong path to version_map

### ISSUE THREAD

**Issue by mheida** [asdf-format/asdf#938]
Hi, possibly stupid question here but I can't figure out if something's wrong or if I've installed something incorrectly. I've installed asdf version 2.7.2 through Conda, and when I try to write an asdf file this error occurs:

```
Traceback (most recent call last):
  File "//miniconda3/envs/envpy3/lib/python3.7/site-packages/asdf/versioning.py", line 53, in get_version_map
    with generic_io.get_file(version_map_path, 'r') as fd:
  File "//miniconda3/envs/envpy3/lib/python3.7/site-packages/asdf/generic_io.py", line 1193, in get_file
    fd = open(realpath, realmode)
FileNotFoundError: [Errno 2] No such file or directory: '/envs/envpy3/lib/python3.7/site-packages/asdf/schemas/stsci.edu/asdf/version_map-1.5.0.yaml'
```

That version map exists but it's located in /miniconda3/envs/..., is there a way to change the default search path?

Thanks!

**Comment by eslavich** [comment]
Hmm... I haven't seen that before.  What OS are you using?  The leading `//` in the traceback file path seems odd but that may be unrelated.

**Comment by mheida** [comment]
I'm on MacOS Mojave. Could be I just need to update something, but I wouldn't know what. My astropy is up-to-date (version 4.2), and I'm using python 3.7.10.

**Comment by jdavies-st** [comment]
I think generally for MacOS these days, you should not be installing Miniconda into the root dir but instead install it into your user home `$HOME` dir.  I.e. I suspect your conda installation is corrupted somehow.

All the recent Anaconda or Miniconda installers install into home dir now.

This has to do with Apple reducing permissions to write files to root dir by applications.  Installing code into subdirs of `$HOME` is much safer and is generally allowed by MacOS.

**Comment by jdavies-st** [comment]
A solution is to move your old installation to a different directory name and reinstall Miniconda and allow it to update your `.bash_profile` or appropriate dotfile for whichever shell you use.  When you then create a new env, it should put it into `$HOME/miniconda3/envs/`.

**Comment by mheida** [comment]
Thanks, reinstalling Miniconda did the trick.
