### ISSUE TITLE
Replace use of pkg_resources with importlib.metadata

### ISSUE THREAD

**Issue by eslavich** [asdf-format/asdf#941]
See discussions:

https://github.com/astropy/astropy/pull/11091
https://github.com/pypa/pip/issues/7413

**Comment by marscher** [comment]
pkg_resources is the devil in terms of package import time.

**Comment by perrygreenfield** [comment]
Have you followed the recommendations at the end of this page? https://asdf.readthedocs.io/en/latest/asdf/extending/resources.html#installing-resources-via-entry-points

**Comment by eslavich** [comment]
We're still supporting Python 3.6 and 3.7, so we'll need to use the [importlib.metadata shim](https://pypi.org/project/importlib-metadata/) in order to do this.

**Comment by nden** [comment]
@WilliamJamieson Can this be closed?
