### ISSUE TITLE
HTTPS and 3xx redirect support

### ISSUE THREAD

**Issue by eslavich** [asdf-format/asdf#965]
This library does not support opening files from https URLs, only http.  This line:

https://github.com/asdf-format/asdf/blob/2.7.3/asdf/generic_io.py#L1065

uses `http.client.HTTPConnection` for all URLs, when it should use HTTPSConnection for https.

We also don't follow redirects -- there's no built-in support for that in http.client.

See https://github.com/astropy/specutils/issues/801 for a traceback when an https URL is passed to asdf.open.

**Comment by jdavies-st** [comment]
https://github.com/asdf-format/asdf/blob/3204cc5bf0ad887abbb91671369db4b5ad52f3cd/asdf/generic_io.py#L827

😂
